# Generated by Django 3.0.2 on 2020-01-27 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_list_group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_working_group', models.BooleanField(default=False)),
                ('email_access', models.BooleanField(default=False)),
                ('mobile_access', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('groups_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticates.List_group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_list_group',
            constraint=models.UniqueConstraint(fields=('user_id', 'groups_id', 'is_working_group', 'is_group'), name='groups_and_lists_diferentiation_key'),
        ),
    ]
